const STRING_EMPTY = "";
const TIME_TOKEN_EXPIRE = 300;
const TOKEN_IS_VALID = true;
const TOKEN_IS_NOT_VALID = false;
const TOKEN_NOT_EXIST = null;

const utils = {
STRING_EMPTY: STRING_EMPTY,
TIME_TOKEN_EXPIRE: TIME_TOKEN_EXPIRE,
TOKEN_IS_VALID: TOKEN_IS_VALID,
TOKEN_IS_NOT_VALID: TOKEN_IS_NOT_VALID,
TOKEN_NOT_EXIST: TOKEN_NOT_EXIST
};

module.exports = utils;