const STATUS_CREATED = 201;
const STATUS_OK = 200;
const STATUS_NOT_FOUND = 404;
const STATUS_ERROR_SERVER = 500;

const STRING_EMPTY = "";

const status = {

STATUS_CREATED: STATUS_CREATED,
STATUS_OK: STATUS_OK,
STATUS_NOT_FOUND: STATUS_NOT_FOUND,
STATUS_ERROR_SERVER: STATUS_ERROR_SERVER,

STRING_EMPTY: STRING_EMPTY

};

module.exports = status;