const STATUS_CREATED = 201;
const STATUS_OK = 200;
const STATUS_Unauthorized = 401;
const STATUS_Forbidden = 403;
const STATUS_NOT_FOUND = 404;
const STATUS_ERROR_SERVER = 500;

const STRING_EMPTY = "";
const TEMPO_TOKEN_EXPIRE = 300;

const status = {

STATUS_CREATED: STATUS_CREATED,
STATUS_OK: STATUS_OK,
STATUS_Unauthorized: STATUS_Unauthorized,
STATUS_Forbidden: STATUS_Forbidden,
STATUS_NOT_FOUND: STATUS_NOT_FOUND,
STATUS_ERROR_SERVER: STATUS_ERROR_SERVER,

STRING_EMPTY: STRING_EMPTY,
TEMPO_TOKEN_EXPIRE: TEMPO_TOKEN_EXPIRE

};

module.exports = status;